# Generated by Django 3.0.8 on 2021-04-29 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_auto_20210426_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_phoneno',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpno', to='Management.Customer'),
        ),
        migrations.AlterField(
            model_name='staff_phoneno',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sphno', to=settings.AUTH_USER_MODEL),
        ),
    ]
