# Generated by Django 3.0.8 on 2021-04-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_auto_20210429_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='times_ordered',
        ),
        migrations.AddField(
            model_name='order_menu',
            name='times_ordered',
            field=models.IntegerField(default=0),
        ),
    ]
