# Generated by Django 3.0.8 on 2021-04-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_auto_20210429_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_menu',
            name='menu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Management.Menu'),
        ),
    ]
