# Generated by Django 3.0.8 on 2021-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0012_auto_20210430_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='timesOrdered',
            field=models.IntegerField(default=0),
        ),
    ]
