# Generated by Django 3.0.8 on 2021-05-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0013_menu_timesordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='day',
            field=models.CharField(max_length=50),
        ),
    ]
