# Generated by Django 3.0.8 on 2021-05-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0015_auto_20210501_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='endTime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='startTime',
            field=models.CharField(max_length=50),
        ),
    ]
