# Generated by Django 3.0.8 on 2021-05-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0017_auto_20210501_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
