# Generated by Django 3.0.8 on 2021-05-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0018_auto_20210501_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
