# Generated by Django 3.0.8 on 2021-05-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0020_auto_20210501_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
