# Generated by Django 3.0.8 on 2021-05-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0021_auto_20210501_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
