# Generated by Django 3.0.8 on 2021-05-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0022_auto_20210501_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[['Manager', 'Manager'], ['Cook', 'Cook'], ['Waiter', 'Waiter'], ['DeliveryBoy', 'DeliveryBoy']], max_length=50),
        ),
    ]
